server:
   port: 8888
spring:
#Configuración para el reto final
  application:
    name: reto-config-service
  cloud:
     config:
       server:
         git:
           uri: https://github.com/OscarBayoRequenaNTT/ConfigServerRepo.git
           default-label: main
           search-paths:
           - 'reto-config-service\.*'
  
#  Antigua configuración para el ejercicio de clase
#  application:
#     name: config-server
#  cloud:
#     config:
#       server:
#         git:
#           uri: https://github.com/OscarBayoRequenaNTT/ConfigServerRepo.git
#           default-label: main
#           search-paths:
#           - '*service*'